### ISSUE TITLE
[Question] Can I re-package your .Net Standard DotSpatial.Projection to an independent nuget ? 

### ISSUE THREAD

**Issue by antoineloos** [ststeiger/DotSpatial#1]
Hello, 

First of all, thanks a lot for your great work. You save my life on my project.
I was deseparate to find a lib that can read Proj4 format on .Net Standard. 
I would like package your version of DotSpatial.Projection to a independent Nuget, are you agree with that ? Or do you want a pull request directly on this repo ?  

thanks

**Comment by ststeiger** [comment]
This repo will be fine.

**Comment by antoineloos** [comment]
https://github.com/ststeiger/DotSpatial/pull/2
